name: Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  pytest:
    name: Pytest
    runs-on: ubuntu-latest
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Abhängigkeiten installieren
        run: pip install pytest-homeassistant-custom-component

      - name: Tests ausführen
        run: pytest
